set_property -dict {LOC W5  IOSTANDARD LVCMOS18} [get_ports {clk}]
set_property -dict {LOC W2  IOSTANDARD LVCMOS18} [get_ports {first_input}]
set_property -dict {LOC T1  IOSTANDARD LVCMOS18} [get_ports {second_input}]
set_property -dict {LOC N3  IOSTANDARD LVCMOS18} [get_ports {output_led}]
set_property -dict {LOC U16 IOSTANDARD LVCMOS18} [get_ports {training_led}]